name: build python

on:
  push:
    branches:
      - '*'

env:
  DOCKER_REGISTRY_REPO: "${{ vars.DOCKER_HUB_REPO }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Set up pipenv
        run: |
          mkdir -p -- "$(pip cache dir)"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.DOCKER_REGISTRY_REPO }}:latest

